// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Js_json = require("bs-platform/lib/js/js_json.js");
var ArrayLabels = require("bs-platform/lib/js/arrayLabels.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Styles$ReactTemplate = require("../Styles.bs.js");
var Activity$ReactTemplate = require("./Activity.bs.js");

var component = ReasonReact.statelessComponent("Activities");

var Graphql_error = Caml_exceptions.create("Activities-ReactTemplate.ActivitiesOnSkill.Graphql_error");

var ppx_printed_query = "query ActivitiesOnSkill($id: ID!)  {\nallActivities(filter: {skill: {id: $id}})  {\nid  \ndescription  \nskill  {\nname  \n}\n}\n}";

function parse(value) {
  var match = Js_json.decodeObject(value);
  if (match) {
    var value$1 = match[0]["allActivities"];
    var match$1 = Js_json.decodeArray(value$1);
    var tmp;
    if (match$1) {
      tmp = match$1[0].map((function (value) {
              var match = Js_json.decodeObject(value);
              if (match) {
                var value$1 = match[0];
                var value$2 = value$1["id"];
                var match$1 = Js_json.decodeString(value$2);
                var tmp;
                if (match$1) {
                  tmp = match$1[0];
                } else {
                  throw Graphql_error;
                }
                var value$3 = value$1["description"];
                var match$2 = Js_json.decodeString(value$3);
                var tmp$1;
                if (match$2) {
                  tmp$1 = match$2[0];
                } else {
                  throw Graphql_error;
                }
                var value$4 = value$1["skill"];
                var match$3 = Js_json.decodeNull(value$4);
                var tmp$2;
                if (match$3) {
                  tmp$2 = /* None */0;
                } else {
                  var match$4 = Js_json.decodeObject(value$4);
                  var tmp$3;
                  if (match$4) {
                    var value$5 = match$4[0]["name"];
                    var match$5 = Js_json.decodeString(value$5);
                    var tmp$4;
                    if (match$5) {
                      tmp$4 = match$5[0];
                    } else {
                      throw Graphql_error;
                    }
                    tmp$3 = {
                      name: tmp$4
                    };
                  } else {
                    throw Graphql_error;
                  }
                  tmp$2 = /* Some */[tmp$3];
                }
                return {
                        id: tmp,
                        description: tmp$1,
                        skill: tmp$2
                      };
              } else {
                throw Graphql_error;
              }
            }));
    } else {
      throw Graphql_error;
    }
    return {
            allActivities: tmp
          };
  } else {
    throw Graphql_error;
  }
}

function json_of_optional(encoder, value) {
  if (value) {
    return Curry._1(encoder, value[0]);
  } else {
    return null;
  }
}

function json_of_array(encoder, value) {
  return value.map(Curry.__1(encoder));
}

function json_of_ID(value) {
  return value;
}

function make(id, _) {
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromList(/* :: */[
                /* tuple */[
                  "id",
                  id
                ],
                /* [] */0
              ]),
          parse: parse
        };
}

function makeWithVariables(variables) {
  var id = variables.id;
  return {
          query: ppx_printed_query,
          variables: Js_dict.fromList(/* :: */[
                /* tuple */[
                  "id",
                  id
                ],
                /* [] */0
              ]),
          parse: parse
        };
}

function ret_type() {
  return /* module */[];
}

var MT_Ret = /* module */[];

var ActivitiesOnSkill = /* module */[
  /* Graphql_error */Graphql_error,
  /* ppx_printed_query */ppx_printed_query,
  /* query */ppx_printed_query,
  /* parse */parse,
  /* json_of_optional */json_of_optional,
  /* json_of_array */json_of_array,
  /* json_of_ID */json_of_ID,
  /* make */make,
  /* makeWithVariables */makeWithVariables,
  /* ret_type */ret_type,
  /* MT_Ret */MT_Ret
];

var ActivitiesQuery = ReasonApollo.CreateQuery([
      ppx_printed_query,
      parse
    ]);

function getSkillName(response) {
  var activities = ArrayLabels.to_list(response.allActivities);
  if (activities) {
    var match = activities[0].skill;
    if (match) {
      return match[0].name;
    } else {
      return "";
    }
  } else {
    return "";
  }
}

function make$1(id, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              var activitiesQuery = make(id, /* () */0);
              return ReasonReact.element(/* None */0, /* None */0, Curry.app(ActivitiesQuery[/* make */3], [
                              /* Some */[activitiesQuery.variables],
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              /* None */0,
                              (function (param) {
                                  var result = param[/* result */0];
                                  var tmp;
                                  if (typeof result === "number") {
                                    tmp = React.createElement("div", undefined, "Loading");
                                  } else if (result.tag) {
                                    var response = result[0];
                                    tmp = React.createElement("div", {
                                          style: Styles$ReactTemplate.activitiesContainer
                                        }, React.createElement("h1", {
                                              style: Styles$ReactTemplate.activitiesTitle
                                            }, getSkillName(response)), $$Array.map((function (activity) {
                                                return ReasonReact.element(/* Some */[activity.id], /* None */0, Activity$ReactTemplate.make(activity.description, /* array */[]));
                                              }), response.allActivities));
                                  } else {
                                    tmp = React.createElement("div", undefined, result[0].message);
                                  }
                                  return React.createElement("div", {
                                              style: Styles$ReactTemplate.main
                                            }, tmp);
                                })
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.ActivitiesOnSkill = ActivitiesOnSkill;
exports.ActivitiesQuery = ActivitiesQuery;
exports.getSkillName = getSkillName;
exports.make = make$1;
/* component Not a pure module */
