// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks = require("reason-apollo/src/ApolloLinks.bs.js");
var ReasonApollo = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* None */0, /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("https://api.graph.cool/simple/v1/civ0m09qx0uss0113an2cp5kj", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var instance = ReasonApollo.createApolloClient(httpLink, inMemoryCache, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

exports.inMemoryCache = inMemoryCache;
exports.httpLink = httpLink;
exports.instance = instance;
/* inMemoryCache Not a pure module */
